[package]
name = "rust_chess"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "rust_chess"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.25.0"
