[package]
name = "rust_chess"
version = "0.1.0"
edition = "2021"

[dependencies]
pyo3 = { version = "0.26.0", features = ["extension-module"] }
rand = "0.9.2"
strum = "0.26"
strum_macros = "0.26"
bitflags = "2.9.4"
once_cell = "1.19"

[profile.release]
debug = true